### ISSUE TITLE
Simple As Possible (SAP-FPU)

### ISSUE THREAD

**Issue by merldsu** [openhwgroup/cvfpu#82]
Hello
@lucabertaccini @MikeOpenHWGroup @pascalgouedo @JeanRochCoulon @jquevremont

We are from Microelectronics Research Lab (MERL-DSU). MERL is an non-profitable organization with an ambitious plan to lead Microelectronics Research & Development in Pakistan. MERL is working with a Vision to enable Pakistan to become a recognized global player in the microelectronics industry. MERL's Mission is to train Undergraduate Students of Pakistan in the field of ASIC designing. 

Our RTL Team has design a Simple as Possible Floating Point Unit (SAP-FPU) based on IEEE-754 format. This is the initial version which contain 22 RISC-V F-Extension Instructions. The design files are available on our github repository. 

https://github.com/merldsu/SAP_FPU.git

Regards:
MERL-DSU

**Comment by MikeOpenHWGroup** [comment]
Hi @merldsu.  Congratulations on the initial release of SAP-FPU.  If you would like to promote this to the OpenHW Group, I would recommend getting in touch with Duncan Bees (@DBees) and discuss the possibility of presenting your work to the Cores Task Group.
